// Build step: run `npm run build` after editing anything in src/.
// 1. Assembles src/pages/*.html with src/partials/* into the site root.
// 2. Collects every Lucide icon the site uses into js/icons.js.
// 3. Bundles src/hero-scene.js (Three.js) into js/hero-scene.js as a classic script.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { createHash } from "node:crypto";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");

const hash = (f) => createHash("sha1").update(readFileSync(join(root, f))).digest("hex").slice(0, 8);
const pages = readdirSync(join(root, "src/pages")).filter((f) => f.endsWith(".html"));

// ---- 1. icons ----
const scanFiles = [
  ...pages.map((f) => `src/pages/${f}`),
  ...readdirSync(join(root, "src/partials")).map((f) => `src/partials/${f}`),
  ...readdirSync(join(root, "js")).filter((f) => f.endsWith(".js") && f !== "icons.js" && f !== "hero-scene.js").map((f) => `js/${f}`),
];
const names = new Set();
for (const f of scanFiles) {
  const src = read(f);
  for (const m of src.matchAll(/data-icon="([a-z0-9-]+)"/g)) names.add(m[1]);
  for (const m of src.matchAll(/icon\(\s*["']([a-z0-9-]+)["']/g)) names.add(m[1]);
  for (const m of src.matchAll(/(?:icon:|empty\()\s*["']([a-z0-9-]+)["']/g)) names.add(m[1]);
}
const icons = {};
for (const n of [...names].sort()) {
  const svg = read(`node_modules/lucide-static/icons/${n}.svg`);
  icons[n] = svg
    .replace(/<!--[\s\S]*?-->/, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/\s*\n\s*/g, "")
    .trim();
}
writeFileSync(
  join(root, "js/icons.js"),
  `/* Generated by scripts/build.mjs from lucide-static (ISC licence). */\nwindow.PATHIK_ICONS=${JSON.stringify(icons)};\n`
);

// ---- 2. hero scene ----
await build({
  entryPoints: [join(root, "src/hero-scene.js")],
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2019",
  outfile: join(root, "js/hero-scene.js"),
  legalComments: "none",
  banner: { js: "/* Pathik hero scene. Three.js r169 (MIT). Source: src/hero-scene.js */" },
});

// ---- 3. pages (last, so asset hashes are final) ----
const partials = Object.fromEntries(
  readdirSync(join(root, "src/partials")).map((f) => [f.replace(".html", ""), read(`src/partials/${f}`)])
);
for (const file of pages) {
  const name = file.replace(".html", "");
  let html = read(`src/pages/${file}`).replace(/<!-- @include (\w+) -->/g, (_, p) => {
    if (!partials[p]) throw new Error(`Missing partial ${p} in ${file}`);
    return partials[p].trim();
  });
  html = html.replace(new RegExp(`data-nav="${name}"`, "g"), `data-nav="${name}" aria-current="page"`);
  // cache-busting: browsers fetch new CSS/JS whenever the file content changes
  html = html.replace(/(href|src)="((?:css|js)\/[\w.-]+\.(?:css|js))"/g, (_, attr, file) => `${attr}="${file}?v=${hash(file)}"`);
  html = html.replace('<html lang="en">', `<html lang="en" data-v="${hash("js/hero-scene.js")}">`);
  writeFileSync(join(root, file), `<!-- Generated from src/pages/${file}. Edit the source, then run npm run build. -->\n${html}`);
}

console.log(`Built ${pages.length} pages, ${names.size} icons, hero scene.`);
