// One-off: simplify the official India outline into js/india-map.js.
// Source: DataMeet "india-composite" (CC BY 4.0), which follows the Survey of India
// boundary: all of Jammu & Kashmir and Ladakh, and Arunachal Pradesh.
// Usage: node scripts/india-map.mjs path/to/india-composite.geojson
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = process.argv[2];
if (!src) throw new Error("Pass the path to india-composite.geojson");
const gj = JSON.parse(readFileSync(src, "utf8"));

const TOL = 0.025; // degrees, about 2.5 km
function dp(pts, tol) {
  if (pts.length < 3) return pts;
  const keep = new Uint8Array(pts.length);
  keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = pts[a], [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay, len = Math.hypot(dx, dy) || 1e-12;
    let best = -1, bi = -1;
    for (let i = a + 1; i < b; i++) {
      const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + bx * ay - by * ax) / len;
      if (d > best) { best = d; bi = i; }
    }
    if (best > tol) { keep[bi] = 1; stack.push([a, bi], [bi, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}
const area = (r) => r.reduce((s, p, i) => { const q = r[(i + 1) % r.length]; return s + p[0] * q[1] - q[0] * p[1]; }, 0) / 2;

const rings = [];
for (const f of gj.features) {
  const polys = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const poly of polys) {
    const outer = poly[0];
    const A = Math.abs(area(outer));
    if (A < 0.00009) continue; // keep the Lakshadweep atolls, drop rocks
    const tol = Math.min(TOL, Math.sqrt(A) * 0.12); // small islands keep their shape
    // split the closed ring in two so the endpoints survive simplification
    const half = Math.floor(outer.length / 2);
    let r = [...dp(outer.slice(0, half + 1), tol), ...dp(outer.slice(half), tol).slice(1)];
    if (r.length > 1 && r[0][0] === r[r.length - 1][0] && r[0][1] === r[r.length - 1][1]) r.pop();
    if (r.length < 4) continue;
    if (area(r) < 0) r.reverse(); // counter-clockwise
    rings.push(r.map(([x, y]) => [+x.toFixed(3), +y.toFixed(3)]));
  }
}
rings.sort((a, b) => Math.abs(area(b)) - Math.abs(area(a)));
const pts = rings.reduce((n, r) => n + r.length, 0);
const out = `/* India outline as published by the Survey of India (includes all of Jammu & Kashmir,
   Ladakh and Arunachal Pradesh). Simplified from "India boundaries" by the DataMeet India
   community, CC BY 4.0: https://github.com/datameet/maps (Country/india-composite.geojson).
   Rings are [lng, lat] pairs, largest first. Generated by scripts/india-map.mjs. */
window.PATHIK_INDIA = ${JSON.stringify(rings)};
`;
writeFileSync(join(root, "js/india-map.js"), out);
console.log(`${rings.length} rings, ${pts} points, ${(out.length / 1024).toFixed(1)} KB`);
